export const cards = [
  {
    id: 0,
    title: 'Сказочное заморское яство',
    titleHoverActive: 'Котэ не одобряет?',
    name: 'Нямушка',
    flavor: 'с фуа-гра',
    advantage: [
      [10, 'порций'],
      ['', 'мышь в подарок'],
    ],
    weight: '0,5',
    selectedText: 'Печень утки разварная с артишоками.',
    disabled: false,
  },
  {
    id: 1,
    title: 'Сказочное заморское яство',
    titleHoverActive: 'Котэ не одобряет?',
    name: 'Нямушка',
    flavor: 'с рыбой',
    advantage: [
      [10, 'порций'],
      [2, 'мыши в подарок'],
    ],
    weight: '2',
    selectedText: 'Головы щучьи с чесноком да свежайшая сёмгушка.',
    disabled: false,
  },
  {
    id: 2,
    title: 'Сказочное заморское яство',
    titleHoverActive: 'Котэ не одобряет?',
    name: 'Нямушка',
    flavor: 'с курой',
    advantage: [
      [100, 'порций'],
      [5, 'мышей в подарок'],
      ['', 'заказчик доволен'],
    ],
    weight: '5',
    selectedText: 'Филе из цыплят с трюфелями в бульоне.',
    disabled: true,
  },
]
